namespace Tdev702.Repository.SQL;

public static class NutrimentQueries
{
   public const string Create = @"
       INSERT INTO shop.nutriments (
           product_id,
           carbohydrates,
           carbohydrates_100g,
           carbohydrates_prepared,
           carbohydrates_prepared_100g,
           carbohydrates_prepared_serving,
           carbohydrates_prepared_unit,
           carbohydrates_prepared_value,
           carbohydrates_serving,
           carbohydrates_unit,
           carbohydrates_value,
           energy,
           energy_kcal,
           energy_kcal_100g,
           energy_kcal_prepared,
           energy_kcal_prepared_100g,
           energy_kcal_prepared_serving,
           energy_kcal_prepared_unit,
           energy_kcal_prepared_value,
           energy_kcal_serving,
           energy_kcal_unit,
           energy_kcal_value,
           energy_kcal_value_computed,
           energy_kj,
           energy_kj_100g,
           energy_kj_prepared,
           energy_kj_prepared_100g,
           energy_kj_prepared_serving,
           energy_kj_prepared_unit,
           energy_kj_prepared_value,
           energy_kj_serving,
           energy_kj_unit,
           energy_kj_value,
           energy_kj_value_computed,
           energy_100g,
           energy_prepared,
           energy_prepared_100g,
           energy_prepared_serving,
           energy_prepared_unit,
           energy_prepared_value,
           energy_serving,
           energy_unit,
           energy_value,
           fat,
           fat_100g,
           fat_prepared,
           fat_prepared_100g,
           fat_prepared_serving,
           fat_prepared_unit,
           fat_prepared_value,
           fat_serving,
           fat_unit,
           fat_value,
           fiber_prepared,
           fiber_prepared_100g,
           fiber_prepared_serving,
           fiber_prepared_unit,
           fiber_prepared_value,
           fruits_vegetables_legumes_estimate_from_ingredients_100g,
           fruits_vegetables_legumes_estimate_from_ingredients_serving,
           fruits_vegetables_nuts_estimate_from_ingredients_100g,
           fruits_vegetables_nuts_estimate_from_ingredients_serving,
           nova_group,
           nova_group_100g,
           nova_group_serving,
           nutrition_score_fr,
           nutrition_score_fr_100g,
           proteins,
           proteins_100g,
           proteins_prepared,
           proteins_prepared_100g,
           proteins_prepared_serving,
           proteins_prepared_unit,
           proteins_prepared_value,
           proteins_serving,
           proteins_unit,
           proteins_value,
           salt,
           salt_100g,
           salt_prepared,
           salt_prepared_100g,
           salt_prepared_serving,
           salt_prepared_unit,
           salt_prepared_value,
           salt_serving,
           salt_unit,
           salt_value,
           saturated_fat,
           saturated_fat_100g,
           saturated_fat_prepared,
           saturated_fat_prepared_100g,
           saturated_fat_prepared_serving,
           saturated_fat_prepared_unit,
           saturated_fat_prepared_value,
           saturated_fat_serving,
           saturated_fat_unit,
           saturated_fat_value,
           sodium,
           sodium_100g,
           sodium_prepared,
           sodium_prepared_100g,
           sodium_prepared_serving,
           sodium_prepared_unit,
           sodium_prepared_value,
           sodium_serving,
           sodium_unit,
           sodium_value,
           sugars,
           sugars_100g,
           sugars_prepared,
           sugars_prepared_100g,
           sugars_prepared_serving,
           sugars_prepared_unit,
           sugars_prepared_value,
           sugars_serving,
           sugars_unit,
           sugars_value
       ) VALUES (
           @ProductId,
           @Carbohydrates,
           @Carbohydrates100G,
           @CarbohydratesPrepared,
           @CarbohydratesPrepared100G,
           @CarbohydratesPreparedServing,
           @CarbohydratesPreparedUnit,
           @CarbohydratesPreparedValue,
           @CarbohydratesServing,
           @CarbohydratesUnit,
           @CarbohydratesValue,
           @Energy,
           @EnergyKcal,
           @EnergyKcal100G,
           @EnergyKcalPrepared,
           @EnergyKcalPrepared100G,
           @EnergyKcalPreparedServing,
           @EnergyKcalPreparedUnit,
           @EnergyKcalPreparedValue,
           @EnergyKcalServing,
           @EnergyKcalUnit,
           @EnergyKcalValue,
           @EnergyKcalValueComputed,
           @EnergyKj,
           @EnergyKj100G,
           @EnergyKjPrepared,
           @EnergyKjPrepared100G,
           @EnergyKjPreparedServing,
           @EnergyKjPreparedUnit,
           @EnergyKjPreparedValue,
           @EnergyKjServing,
           @EnergyKjUnit,
           @EnergyKjValue,
           @EnergyKjValueComputed,
           @Energy100G,
           @EnergyPrepared,
           @EnergyPrepared100G,
           @EnergyPreparedServing,
           @EnergyPreparedUnit,
           @EnergyPreparedValue,
           @EnergyServing,
           @EnergyUnit,
           @EnergyValue,
           @Fat,
           @Fat100G,
           @FatPrepared,
           @FatPrepared100G,
           @FatPreparedServing,
           @FatPreparedUnit,
           @FatPreparedValue,
           @FatServing,
           @FatUnit,
           @FatValue,
           @FiberPrepared,
           @FiberPrepared100G,
           @FiberPreparedServing,
           @FiberPreparedUnit,
           @FiberPreparedValue,
           @FruitsVegetablesLegumesEstimateFromIngredients100G,
           @FruitsVegetablesLegumesEstimateFromIngredientsServing,
           @FruitsVegetablesNutsEstimateFromIngredients100G,
           @FruitsVegetablesNutsEstimateFromIngredientsServing,
           @NovaGroup,
           @NovaGroup100G,
           @NovaGroupServing,
           @NutritionScoreFr,
           @NutritionScoreFr100G,
           @Proteins,
           @Proteins100G,
           @ProteinsPrepared,
           @ProteinsPrepared100G,
           @ProteinsPreparedServing,
           @ProteinsPreparedUnit,
           @ProteinsPreparedValue,
           @ProteinsServing,
           @ProteinsUnit,
           @ProteinsValue,
           @Salt,
           @Salt100G,
           @SaltPrepared,
           @SaltPrepared100G,
           @SaltPreparedServing,
           @SaltPreparedUnit,
           @SaltPreparedValue,
           @SaltServing,
           @SaltUnit,
           @SaltValue,
           @SaturatedFat,
           @SaturatedFat100G,
           @SaturatedFatPrepared,
           @SaturatedFatPrepared100G,
           @SaturatedFatPreparedServing,
           @SaturatedFatPreparedUnit,
           @SaturatedFatPreparedValue,
           @SaturatedFatServing,
           @SaturatedFatUnit,
           @SaturatedFatValue,
           @Sodium,
           @Sodium100G,
           @SodiumPrepared,
           @SodiumPrepared100G,
           @SodiumPreparedServing,
           @SodiumPreparedUnit,
           @SodiumPreparedValue,
           @SodiumServing,
           @SodiumUnit,
           @SodiumValue,
           @Sugars,
           @Sugars100G,
           @SugarsPrepared,
           @SugarsPrepared100G,
           @SugarsPreparedServing,
           @SugarsPreparedUnit,
           @SugarsPreparedValue,
           @SugarsServing,
           @SugarsUnit,
           @SugarsValue
       )
       RETURNING id";

   public const string Update = @"
       UPDATE shop.nutriments 
       SET 
           carbohydrates = COALESCE(@Carbohydrates, carbohydrates),
           carbohydrates_100g = COALESCE(@Carbohydrates100G, carbohydrates_100g),
           carbohydrates_prepared = COALESCE(@CarbohydratesPrepared, carbohydrates_prepared),
           carbohydrates_prepared_100g = COALESCE(@CarbohydratesPrepared100G, carbohydrates_prepared_100g),
           carbohydrates_prepared_serving = COALESCE(@CarbohydratesPreparedServing, carbohydrates_prepared_serving),
           carbohydrates_prepared_unit = COALESCE(@CarbohydratesPreparedUnit, carbohydrates_prepared_unit),
           carbohydrates_prepared_value = COALESCE(@CarbohydratesPreparedValue, carbohydrates_prepared_value),
           carbohydrates_serving = COALESCE(@CarbohydratesServing, carbohydrates_serving),
           carbohydrates_unit = COALESCE(@CarbohydratesUnit, carbohydrates_unit),
           carbohydrates_value = COALESCE(@CarbohydratesValue, carbohydrates_value),
           energy = COALESCE(@Energy, energy),
           energy_kcal = COALESCE(@EnergyKcal, energy_kcal),
           energy_kcal_100g = COALESCE(@EnergyKcal100G, energy_kcal_100g),
           energy_kcal_prepared = COALESCE(@EnergyKcalPrepared, energy_kcal_prepared),
           energy_kcal_prepared_100g = COALESCE(@EnergyKcalPrepared100G, energy_kcal_prepared_100g),
           energy_kcal_prepared_serving = COALESCE(@EnergyKcalPreparedServing, energy_kcal_prepared_serving),
           energy_kcal_prepared_unit = COALESCE(@EnergyKcalPreparedUnit, energy_kcal_prepared_unit),
           energy_kcal_prepared_value = COALESCE(@EnergyKcalPreparedValue, energy_kcal_prepared_value),
           energy_kcal_serving = COALESCE(@EnergyKcalServing, energy_kcal_serving),
           energy_kcal_unit = COALESCE(@EnergyKcalUnit, energy_kcal_unit),
           energy_kcal_value = COALESCE(@EnergyKcalValue, energy_kcal_value),
           energy_kcal_value_computed = COALESCE(@EnergyKcalValueComputed, energy_kcal_value_computed),
           energy_kj = COALESCE(@EnergyKj, energy_kj),
           energy_kj_100g = COALESCE(@EnergyKj100G, energy_kj_100g),
           energy_kj_prepared = COALESCE(@EnergyKjPrepared, energy_kj_prepared),
           energy_kj_prepared_100g = COALESCE(@EnergyKjPrepared100G, energy_kj_prepared_100g),
           energy_kj_prepared_serving = COALESCE(@EnergyKjPreparedServing, energy_kj_prepared_serving),
           energy_kj_prepared_unit = COALESCE(@EnergyKjPreparedUnit, energy_kj_prepared_unit),
           energy_kj_prepared_value = COALESCE(@EnergyKjPreparedValue, energy_kj_prepared_value),
           energy_kj_serving = COALESCE(@EnergyKjServing, energy_kj_serving),
           energy_kj_unit = COALESCE(@EnergyKjUnit, energy_kj_unit),
           energy_kj_value = COALESCE(@EnergyKjValue, energy_kj_value),
           energy_kj_value_computed = COALESCE(@EnergyKjValueComputed, energy_kj_value_computed),
           energy_100g = COALESCE(@Energy100G, energy_100g),
           energy_prepared = COALESCE(@EnergyPrepared, energy_prepared),
           energy_prepared_100g = COALESCE(@EnergyPrepared100G, energy_prepared_100g),
           energy_prepared_serving = COALESCE(@EnergyPreparedServing, energy_prepared_serving),
           energy_prepared_unit = COALESCE(@EnergyPreparedUnit, energy_prepared_unit),
           energy_prepared_value = COALESCE(@EnergyPreparedValue, energy_prepared_value),
           energy_serving = COALESCE(@EnergyServing, energy_serving),
           energy_unit = COALESCE(@EnergyUnit, energy_unit),
           energy_value = COALESCE(@EnergyValue, energy_value),
           fat = COALESCE(@Fat, fat),
           fat_100g = COALESCE(@Fat100G, fat_100g),
           fat_prepared = COALESCE(@FatPrepared, fat_prepared),
           fat_prepared_100g = COALESCE(@FatPrepared100G, fat_prepared_100g),
           fat_prepared_serving = COALESCE(@FatPreparedServing, fat_prepared_serving),
           fat_prepared_unit = COALESCE(@FatPreparedUnit, fat_prepared_unit),
           fat_prepared_value = COALESCE(@FatPreparedValue, fat_prepared_value),
           fat_serving = COALESCE(@FatServing, fat_serving),
           fat_unit = COALESCE(@FatUnit, fat_unit),
           fat_value = COALESCE(@FatValue, fat_value),
           fiber_prepared = COALESCE(@FiberPrepared, fiber_prepared),
           fiber_prepared_100g = COALESCE(@FiberPrepared100G, fiber_prepared_100g),
           fiber_prepared_serving = COALESCE(@FiberPreparedServing, fiber_prepared_serving),
           fiber_prepared_unit = COALESCE(@FiberPreparedUnit, fiber_prepared_unit),
           fiber_prepared_value = COALESCE(@FiberPreparedValue, fiber_prepared_value),
           fruits_vegetables_legumes_estimate_from_ingredients_100g = COALESCE(@FruitsVegetablesLegumesEstimateFromIngredients100G, fruits_vegetables_legumes_estimate_from_ingredients_100g),
           fruits_vegetables_legumes_estimate_from_ingredients_serving = COALESCE(@FruitsVegetablesLegumesEstimateFromIngredientsServing, fruits_vegetables_legumes_estimate_from_ingredients_serving),
            fruits_vegetables_nuts_estimate_from_ingredients_100g = COALESCE(@FruitsVegetablesNutsEstimateFromIngredients100G, fruits_vegetables_nuts_estimate_from_ingredients_100g),
           fruits_vegetables_nuts_estimate_from_ingredients_serving = COALESCE(@FruitsVegetablesNutsEstimateFromIngredientsServing, fruits_vegetables_nuts_estimate_from_ingredients_serving),
           nova_group = COALESCE(@NovaGroup, nova_group),
           nova_group_100g = COALESCE(@NovaGroup100G, nova_group_100g),
           nova_group_serving = COALESCE(@NovaGroupServing, nova_group_serving),
           nutrition_score_fr = COALESCE(@NutritionScoreFr, nutrition_score_fr),
           nutrition_score_fr_100g = COALESCE(@NutritionScoreFr100G, nutrition_score_fr_100g),
           proteins = COALESCE(@Proteins, proteins),
           proteins_100g = COALESCE(@Proteins100G, proteins_100g),
           proteins_prepared = COALESCE(@ProteinsPrepared, proteins_prepared),
           proteins_prepared_100g = COALESCE(@ProteinsPrepared100G, proteins_prepared_100g),
           proteins_prepared_serving = COALESCE(@ProteinsPreparedServing, proteins_prepared_serving),
           proteins_prepared_unit = COALESCE(@ProteinsPreparedUnit, proteins_prepared_unit),
           proteins_prepared_value = COALESCE(@ProteinsPreparedValue, proteins_prepared_value),
           proteins_serving = COALESCE(@ProteinsServing, proteins_serving),
           proteins_unit = COALESCE(@ProteinsUnit, proteins_unit),
           proteins_value = COALESCE(@ProteinsValue, proteins_value),
           salt = COALESCE(@Salt, salt),
           salt_100g = COALESCE(@Salt100G, salt_100g),
           salt_prepared = COALESCE(@SaltPrepared, salt_prepared),
           salt_prepared_100g = COALESCE(@SaltPrepared100G, salt_prepared_100g),
           salt_prepared_serving = COALESCE(@SaltPreparedServing, salt_prepared_serving),
           salt_prepared_unit = COALESCE(@SaltPreparedUnit, salt_prepared_unit),
           salt_prepared_value = COALESCE(@SaltPreparedValue, salt_prepared_value),
           salt_serving = COALESCE(@SaltServing, salt_serving),
           salt_unit = COALESCE(@SaltUnit, salt_unit),
           salt_value = COALESCE(@SaltValue, salt_value),
           saturated_fat = COALESCE(@SaturatedFat, saturated_fat),
           saturated_fat_100g = COALESCE(@SaturatedFat100G, saturated_fat_100g),
           saturated_fat_prepared = COALESCE(@SaturatedFatPrepared, saturated_fat_prepared),
           saturated_fat_prepared_100g = COALESCE(@SaturatedFatPrepared100G, saturated_fat_prepared_100g),
           saturated_fat_prepared_serving = COALESCE(@SaturatedFatPreparedServing, saturated_fat_prepared_serving),
           saturated_fat_prepared_unit = COALESCE(@SaturatedFatPreparedUnit, saturated_fat_prepared_unit),
           saturated_fat_prepared_value = COALESCE(@SaturatedFatPreparedValue, saturated_fat_prepared_value),
           saturated_fat_serving = COALESCE(@SaturatedFatServing, saturated_fat_serving),
           saturated_fat_unit = COALESCE(@SaturatedFatUnit, saturated_fat_unit),
           saturated_fat_value = COALESCE(@SaturatedFatValue, saturated_fat_value),
           sodium = COALESCE(@Sodium, sodium),
           sodium_100g = COALESCE(@Sodium100G, sodium_100g),
           sodium_prepared = COALESCE(@SodiumPrepared, sodium_prepared),
           sodium_prepared_100g = COALESCE(@SodiumPrepared100G, sodium_prepared_100g),
           sodium_prepared_serving = COALESCE(@SodiumPreparedServing, sodium_prepared_serving),
           sodium_prepared_unit = COALESCE(@SodiumPreparedUnit, sodium_prepared_unit),
           sodium_prepared_value = COALESCE(@SodiumPreparedValue, sodium_prepared_value),
           sodium_serving = COALESCE(@SodiumServing, sodium_serving),
           sodium_unit = COALESCE(@SodiumUnit, sodium_unit),
           sodium_value = COALESCE(@SodiumValue, sodium_value),
           sugars = COALESCE(@Sugars, sugars),
           sugars_100g = COALESCE(@Sugars100G, sugars_100g),
           sugars_prepared = COALESCE(@SugarsPrepared, sugars_prepared),
           sugars_prepared_100g = COALESCE(@SugarsPrepared100G, sugars_prepared_100g),
           sugars_prepared_serving = COALESCE(@SugarsPreparedServing, sugars_prepared_serving),
           sugars_prepared_unit = COALESCE(@SugarsPreparedUnit, sugars_prepared_unit),
           sugars_prepared_value = COALESCE(@SugarsPreparedValue, sugars_prepared_value),
           sugars_serving = COALESCE(@SugarsServing, sugars_serving),
           sugars_unit = COALESCE(@SugarsUnit, sugars_unit),
           sugars_value = COALESCE(@SugarsValue, sugars_value)
       WHERE product_id = @ProductId";
   
   public const string GetByProductId = @"
       SELECT *
       FROM shop.nutriments
       WHERE product_id = @ProductId";
}